apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-case
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-case
  template:
    metadata:
      labels:
        app: test-case
    spec:
      containers:
        - name: test-case-container
          image: 975050196742.dkr.ecr.eu-central-1.amazonaws.com/insider/test-case:latest
          command: ['sh', '-c', 'echo The app is running! && sleep 3600']
          ports:
            - containerPort: 80
            - containerPort: 443
      imagePullSecrets:
        - name: regcred