apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-pod
  labels:
    app: selenium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium
  template:
    metadata:
      labels:
        app: selenium
    spec:
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      containers:
        - name: selenium-hub
          image: selenium/hub:4.0
          ports:
            - containerPort: 4444
            - containerPort: 4443
            - containerPort: 4442
          livenessProbe:
            httpGet:
              path: /wd/hub/status
              port: 4444
            initialDelaySeconds: 40
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /wd/hub/status
              port: 4444
            initialDelaySeconds: 40
            timeoutSeconds: 5

        - name: selenium-node-chrome
          image: selenium/node-chrome:latest
          ports:
            - containerPort: 5555
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          env:
            - name: SE_EVENT_BUS_HOST
              value: "localhost"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"

---
apiVersion: v1
kind: Service
metadata:
  name: selenium-service
  labels:
    app: selenium
spec:
  selector:
    app: selenium
  ports:
    - port: 4444
      targetPort: 4444
      name: hub
    - port: 5555
      targetPort: 5555
      name: node-chrome
  type: ClusterIP