apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-case
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-case
  template:
    metadata:
      labels:
        app: test-case
    spec:
      containers:
        - name: test-case-container
          image: public.ecr.aws/a5i9j0w3/insider-public-repository/test-case:latest
          command: ['sh', '-c', 'echo The app is running! && sleep 3600']
          ports:
            - containerPort: 80
            - containerPort: 443